"""initial schema

Revision ID: 0205f7d6785b
Revises: 
Create Date: 2026-09-20 11:29:37.445957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0205f7d6785b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_auc', sa.Float(), nullable=False),
    sa.Column('paper_baseline_auc', sa.Float(), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scoring_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version'], ['model_versions.version'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_requests_created_at'), 'scoring_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_scoring_requests_decision'), 'scoring_requests', ['decision'], unique=False)
    op.create_index(op.f('ix_scoring_requests_deleted_at'), 'scoring_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_scoring_requests_predicted_probability'), 'scoring_requests', ['predicted_probability'], unique=False)
    op.create_index(op.f('ix_scoring_requests_user_id'), 'scoring_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_requests_user_id'), table_name='scoring_requests')
    op.drop_index(op.f('ix_scoring_requests_predicted_probability'), table_name='scoring_requests')
    op.drop_index(op.f('ix_scoring_requests_deleted_at'), table_name='scoring_requests')
    op.drop_index(op.f('ix_scoring_requests_decision'), table_name='scoring_requests')
    op.drop_index(op.f('ix_scoring_requests_created_at'), table_name='scoring_requests')
    op.drop_table('scoring_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
